AspSolution/WebApp/Controllers/AppUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain.App.Identity;

namespace WebApp.Controllers
{
    public class AppUsersController : Controller
    {
        private readonly AppDbContext _context;

        public AppUsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: AppUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.AppUsers.ToListAsync());
        }

        // GET: AppUsers/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appUser == null)
            {
                return NotFound();
            }

            return View(appUser);
        }

        // GET: AppUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AppUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,ProfileId,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] AppUser appUser)
        {
            if (ModelState.IsValid)
            {
                appUser.Id = Guid.NewGuid();
                _context.Add(appUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(appUser);
        }

        // GET: AppUsers/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers.FindAsync(id);
            if (appUser == null)
            {
                return NotFound();
            }
            return View(appUser);
        }

        // POST: AppUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("FirstName,LastName,ProfileId,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] AppUser appUser)
        {
            if (id != appUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppUserExists(appUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(appUser);
        }

        // GET: AppUsers/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appUser = await _context.AppUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appUser == null)
            {
                return NotFound();
            }

            return View(appUser);
        }

        // POST: AppUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var appUser = await _context.AppUsers.FindAsync(id);
            _context.AppUsers.Remove(appUser);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppUserExists(Guid id)
        {
            return _context.AppUsers.Any(e => e.Id == id);
        }
    }
}

AspSolution/WebApp/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain.App;

namespace WebApp.Controllers
{
    public class GradesController : Controller
    {
        private readonly AppDbContext _context;

        public GradesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Grades
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Grades.Include(g => g.AppUser).Include(g => g.GradeSubject).Include(g => g.GradeType).Include(g => g.PossibleGrade).Include(g => g.Profile);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Grades/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades
                .Include(g => g.AppUser)
                .Include(g => g.GradeSubject)
                .Include(g => g.GradeType)
                .Include(g => g.PossibleGrade)
                .Include(g => g.Profile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // GET: Grades/Create
        public IActionResult Create()
        {
            ViewData["AppUserId"] = new SelectList(_context.AppUsers, "Id", "FirstName");
            ViewData["GradeSubjectId"] = new SelectList(_context.Subjects, "Id", "SubjectCode");
            ViewData["GradeTypeId"] = new SelectList(_context.GradeTypes, "Id", "GradeTypeName");
            ViewData["PossibleGradeId"] = new SelectList(_context.PossibleGrades, "Id", "GradeName");
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "LastName");
            return View();
        }

        // POST: Grades/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Description,PossibleGradeId,GradeSubjectId,ProfileId,GradeTypeId,AppUserId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Grade grade)
        {
            if (ModelState.IsValid)
            {
                grade.Id = Guid.NewGuid();
                _context.Add(grade);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUsers, "Id", "FirstName", grade.AppUserId);
            ViewData["GradeSubjectId"] = new SelectList(_context.Subjects, "Id", "SubjectCode", grade.GradeSubjectId);
            ViewData["GradeTypeId"] = new SelectList(_context.GradeTypes, "Id", "GradeTypeName", grade.GradeTypeId);
            ViewData["PossibleGradeId"] = new SelectList(_context.PossibleGrades, "Id", "GradeName", grade.PossibleGradeId);
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "LastName", grade.ProfileId);
            return View(grade);
        }

        // GET: Grades/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades.FindAsync(id);
            if (grade == null)
            {
                return NotFound();
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUsers, "Id", "FirstName", grade.AppUserId);
            ViewData["GradeSubjectId"] = new SelectList(_context.Subjects, "Id", "SubjectCode", grade.GradeSubjectId);
            ViewData["GradeTypeId"] = new SelectList(_context.GradeTypes, "Id", "GradeTypeName", grade.GradeTypeId);
            ViewData["PossibleGradeId"] = new SelectList(_context.PossibleGrades, "Id", "GradeName", grade.PossibleGradeId);
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "LastName", grade.ProfileId);
            return View(grade);
        }

        // POST: Grades/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Description,PossibleGradeId,GradeSubjectId,ProfileId,GradeTypeId,AppUserId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Grade grade)
        {
            if (id != grade.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GradeExists(grade.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AppUserId"] = new SelectList(_context.AppUsers, "Id", "FirstName", grade.AppUserId);
            ViewData["GradeSubjectId"] = new SelectList(_context.Subjects, "Id", "SubjectCode", grade.GradeSubjectId);
            ViewData["GradeTypeId"] = new SelectList(_context.GradeTypes, "Id", "GradeTypeName", grade.GradeTypeId);
            ViewData["PossibleGradeId"] = new SelectList(_context.PossibleGrades, "Id", "GradeName", grade.PossibleGradeId);
            ViewData["ProfileId"] = new SelectList(_context.Profiles, "Id", "LastName", grade.ProfileId);
            return View(grade);
        }

        // GET: Grades/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var grade = await _context.Grades
                .Include(g => g.AppUser)
                .Include(g => g.GradeSubject)
                .Include(g => g.GradeType)
                .Include(g => g.PossibleGrade)
                .Include(g => g.Profile)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (grade == null)
            {
                return NotFound();
            }

            return View(grade);
        }

        // POST: Grades/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var grade = await _context.Grades.FindAsync(id);
            _context.Grades.Remove(grade);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GradeExists(Guid id)
        {
            return _context.Grades.Any(e => e.Id == id);
        }
    }
}

AspSolution/WebApp/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAL.App.EF;
using Domain.App;

namespace WebApp.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly AppDbContext _context;

        public SubjectsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Subjects.Include(s => s.SubjectSemester);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .Include(s => s.SubjectSemester)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            ViewData["SubjectSemesterId"] = new SelectList(_context.Semesters, "Id", "SemesterName");
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SubjectName,SubjectCode,SubjectSemesterId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                subject.Id = Guid.NewGuid();
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectSemesterId"] = new SelectList(_context.Semesters, "Id", "SemesterName", subject.SubjectSemesterId);
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            ViewData["SubjectSemesterId"] = new SelectList(_context.Semesters, "Id", "SemesterName", subject.SubjectSemesterId);
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("SubjectName,SubjectCode,SubjectSemesterId,CreatedBy,CreatedAt,ChangedBy,ChangedAt,Id")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectSemesterId"] = new SelectList(_context.Semesters, "Id", "SemesterName", subject.SubjectSemesterId);
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .Include(s => s.SubjectSemester)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var subject = await _context.Subjects.FindAsync(id);
            _context.Subjects.Remove(subject);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(Guid id)
        {
            return _context.Subjects.Any(e => e.Id == id);
        }
    }
}

AspSolution/WebApp/Views/Shared/_LanguageSelection.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@using Microsoft.AspNetCore.Builder
@inject IOptions<RequestLocalizationOptions> LocalizationOptions
@{
    var cultureItems = LocalizationOptions.Value.SupportedUICultures
        .Select(c => new {Value = c.Name, Text = c.NativeName}).ToList();
}

<li class="nav-item dropdown">
    <a class="nav-link text-dark dropdown-toggle" href="javascript:{}" id="navbarLangDropdown" role="button" data-toggle="dropdown">@Resources.Views.Shared._Layout.Language</a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarLangDropdown">
        @foreach (var item in cultureItems)
        {
            <a class="dropdown-item text-dark"
               asp-area="" asp-controller="Home" asp-action="SetLanguage" asp-route-culture="@item.Value"
               asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">
                @item.Text
            </a>
        }
    </div>
</li>

AspSolution/WebApp/Views/Shared/_Layout.cshtml
@using System.Threading
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>

    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/> *@

    <link rel="stylesheet" href="~/dist/site.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Publisher</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Developer" asp-action="Index">Developer</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="GameCategory" asp-action="Index">GameCategory</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Store</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="GameInStore" asp-action="Index">GameInStore</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="StoreReview" asp-action="Index">StoreReview</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="GameReview" asp-action="Index">GameReview</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Rating" asp-action="Index">Rating</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="GameCategory" asp-action="Index">GameCategories</a> *@
                    @* </li> *@
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdownAdmin" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @Resources.Views.Shared._Layout.Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownAdmin">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AppUsers" asp-action="Index">AppUsers</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Grades" asp-action="Index">Grades</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="personRoles" asp-action="Index">PresonRoles</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="Index">Profiles</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Semesters" asp-action="Index">Semesters</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserSubjects" asp-action="Index">UserSubjects</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="PossibleGrades" asp-action="Index">PossibleGrades</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="GradeTypes" asp-action="Index">GradeTypes</a>
                                @* <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="LangStrTranslations" asp-action="Index">langStrTranslation</a> *@
                                @* <a class="dropdown-item text-dark" asp-area="Admin" asp-controller="LangStr" asp-action="Index">LangStr</a> *@
                                <div class="dropdown-divider"></div>
                            </div>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> Culture: @Thread.CurrentThread.CurrentCulture.Name UICulture: @Thread.CurrentThread.CurrentUICulture.Name
    </div>
</footer>

@* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
@* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> *@

<script src="~/dist/site.js" asp-append-version="true"></script>
<script src="~/dist/jquery.validate.globalize.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)

@{
    var currentCultureCode = Thread.CurrentThread.CurrentCulture.Name.Split('-')[0];
    var datePattern = Thread.CurrentThread.CurrentUICulture.DateTimeFormat.ShortDatePattern;
    datePattern = datePattern
        .Replace("dd", "d")
        .Replace("MM", "m")
        .Replace("yyyy", "Y");
    // LongTimePattern and ShortTimePattern HH:mm for 23:59,  h:mm tt for 11:59 PM
    var timePattern = Thread.CurrentThread.CurrentUICulture.DateTimeFormat.ShortTimePattern;
    var clock24H = timePattern
        .Contains("tt") == false;
    timePattern = timePattern
        .Replace("HH", "H")
        .Replace("mm", "i")
        .Replace("ss", "S")
        .Replace("tt", "K");
    var dateTimePattern = timePattern + " " + datePattern;
}
<script>
    // https://github.com/globalizejs/globalize#installation
    $.when(
        $.get("/dist/cldr-core/supplemental/likelySubtags.json"),
        $.get("/dist/cldr-core/supplemental/numberingSystems.json"),
        $.get("/dist/cldr-core/supplemental/timeData.json"),
        $.get("/dist/cldr-core/supplemental/weekData.json"),
        
        $.get("/dist/cldr-numbers-modern/main/@currentCultureCode/numbers.json"),
        $.get("/dist/cldr-numbers-modern/main/@currentCultureCode/currencies.json"),
        
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/ca-generic.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/ca-gregorian.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/dateFields.json"),
        $.get("/dist/cldr-dates-modern/main/@currentCultureCode/timeZoneNames.json")
    ).then(function () {
        // Normalize $.get results, we only need the JSON, not the request statuses.
        return [].slice.apply(arguments, [0]).map(function (result) {
            return result[0];
        });
    }).then(
        Globalize.load
    ).then(function () {
        // Initialise Globalize to the current culture
        Globalize.locale('@currentCultureCode');
    });
    
    $(function () {
        $('[type="datetime-local"]').each(function (index, value) {
            $(value).attr('type', 'text');
            $(value).val(value.defaultValue);
		    $(value).flatpickr({
		        locale: "@currentCultureCode",
		        enableTime: true,
	    	    altFormat: "@dateTimePattern",
	    	    altInput: true,
	    	    dateFormat: "Z", // iso format
	    	    disableMobile: true,
	    	    time_24hr: @(clock24H.ToString().ToLower()),
		    });
        });

        $('[type="time"]').each(function (index, value) {
            $(value).attr('type', 'text');
            $(value).val(value.defaultValue);
		    $(value).flatpickr({
	    	    locale: "@currentCultureCode",
	    	    enableTime: true,
	    	    noCalendar: true,

	    	    altFormat: "@timePattern",
	    	    altInput: true,
	    	    dateFormat: "H:i", // 24h HH:mm
	    	    disableMobile: true,

	    	    time_24hr: @(clock24H.ToString().ToLower()),
		    });
        });

        $('[type="date"]').each(function (index, value) {
		    $(value).attr('type', 'text');
		    $(value).val(value.defaultValue);
		    $(value).flatpickr({
    		    locale: "@currentCultureCode",
	    	    altFormat: "@datePattern",
	    	    altInput: true,
                disableMobile: true,
	    	    dateFormat: "Y-m-d", // YYYY-MM-DD
		    });
        });
    });
</script>

</body >
</html >